---
title: Tensors 
---

## What are Tensors?

PyTorch provides tensors as its primary data structure. Tensors are similar to numpy arrays, but they can be used on a GPU to accelerate the computation. PyTorch tensors are similar to numpy arrays, but they have additional functionality (automatic differentiation) and are designed to take advantage of GPUs for acceleration. Similar to numpy, tensors in PyTorch supports a variety of operations, including indexing, slicing, math operations, linear algebra operations, and more. Let's dive in by importing the library.  

In [2]:
import torch
import numpy as np

## Initializing a Tensor

There are several ways to initialize tensors in PyTorch. Here are some examples:

**Initializing from an iterator like a list**



In [8]:
import torch

# Initialize a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("Tensor from list: \n", tensor_from_list)

# Initialize a tensor from a nested list
tensor_from_nested_list = torch.tensor([[1, 2], [3, 4]])
print("Tensor from nested list: \n", tensor_from_nested_list)

Tensor from list: 
 tensor([1, 2, 3, 4])
Tensor from nested list: 
 tensor([[1, 2],
        [3, 4]])


**Initializing from a numpy array**

In [9]:
# Create a NumPy array
numpy_array = np.array([[1, 2], [3, 4]])

# Initialize a tensor from a NumPy array
tensor_from_numpy = torch.from_numpy(numpy_array)
print("Tensor from np array: \n", tensor_from_numpy)

Tensor from np array: 
 tensor([[1, 2],
        [3, 4]])


**Initializing from another tensor**

In [13]:
# Create a tensor
original_tensor = torch.tensor([1, 2, 3, 4])

# Initialize a new tensor from the original tensor
new_tensor = original_tensor.clone()
print("Tensor from another tensor: \n", new_tensor)

Tensor from another tensor: 
 tensor([1, 2, 3, 4])


**Constant or random initialization**

In [15]:
# Initialize a tensor with all elements set to zero
tensor_zeros = torch.zeros(3, 4)
print("Tensor with all elements set to zero: \n", tensor_zeros)

# Initialize a tensor with all elements set to one
tensor_ones = torch.ones(3, 4)
print("\n Tensor with all elements set to one: \n", tensor_ones)

# Initialize a tensor with all elements set to a specific value
tensor_full = torch.full((3, 4), fill_value=2.5)
print("\n Tensor with all elements set to a specific value: \n", tensor_full)

# Initialize a tensor with random values
tensor_rand = torch.rand(3, 4)
print("\n Tensor with random initialization: \n", tensor_rand)

# Initialize a tensor with random values from a normal distribution
tensor_randn = torch.randn(3, 4)
print("\n Tensor with random values from a normal distribution: \n", tensor_randn)

Tensor with all elements set to zero: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

 Tensor with all elements set to one: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 Tensor with all elements set to a specific value: 
 tensor([[2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000]])

 Tensor with random initialization: 
 tensor([[0.8675, 0.0161, 0.5472, 0.7002],
        [0.6551, 0.3049, 0.4088, 0.6341],
        [0.2363, 0.8951, 0.0335, 0.5779]])

 Tensor with random values from a normal distribution: 
 tensor([[ 1.0550,  0.9214, -1.3023,  0.4119],
        [-0.4691,  0.8733,  0.7910, -2.3932],
        [-0.6304, -0.8792,  0.4188,  0.4221]])


## Tensor Attributes

It has several attributes that you can access to get information about the tensor. Here are some common attributes of a PyTorch tensor:

- `shape`: returns the shape of the tensor as a tuple of integers. For example, if the tensor has dimensions (batch_size, num_channels, height, width), the shape would be (batch_size, num_channels, height, width).
- `dtype`: returns the data type of the tensor. For example, the data type could be torch.float32 or torch.int64.
- `device`: returns the device on which the tensor is stored. This can be the CPU or a GPU.
- `requires_grad`: a boolean flag indicating whether the tensor requires gradient computation. If set to True, the tensor's gradients will be computed during backpropagation.
- `grad`: a tensor containing the gradient of the tensor with respect to some scalar value. This attribute is typically used during training with gradient descent.

You can access these attributes by calling them on a tensor object. For example:

In [20]:
tensor_randn = torch.randn(3, 4)
print(f"Shape of tensor : {tensor_randn.shape}")
print(f"Type of tensor : {tensor_randn.dtype}")
print(f"Device tensor is stored on : {tensor_randn.device}")
print(f"Autograd enabled : {tensor_randn.requires_grad}")
print(f"Any stored gradient : {tensor_randn.grad}")

Shape of tensor : torch.Size([3, 4])
Type of tensor : torch.float32
Device tensor is stored on : cpu
Autograd enabled : False
Any stored gradient : None


As we can see above we initialized a random tensor of shape (3,4) with a torch.float32 data type and its currently on a cpu device. Currently, automatic gradient calculations are disabled and no gradient is stored in the tensor. 

There are several other attributes that you can access, such as `ndim`, `size`, `numel`, `storage`, etc. You can find more information about these attributes in the [PyTorch Tensor documentation](https://pytorch.org/docs/stable/tensors.html).

## Tensor Operations

There are several operations you can perform on tensors, lets look at the most commonly used operations.

### Moving tensor from CPU to GPU

To move a tensor from CPU to GPU is a simple command but probably the one which people will use the most.

In [23]:
tensor_randn.to("cuda")

tensor([[-0.0984, -1.3804,  0.3343, -0.1623],
        [ 0.9155, -0.8620, -0.3943, -0.2997],
        [-0.1336, -0.7395, -0.7143, -0.0735]], device='cuda:0')

As we can see the tensor_randn is now moved to a cuda(GPU) device.

### Slicing and Indexing

PyTorch tensors similar to numpy arrays support various slicing and indexing operations.

In [38]:
tensor_randn = torch.randn(3, 4)
tensor_randn

tensor([[-1.3470,  0.2204,  0.2963, -0.9745],
        [ 0.1867, -1.8338, -1.1872, -1.2987],
        [ 0.0517, -0.3206,  0.3584, -0.4778]])

In [39]:
print(f"First row:  \n{tensor_randn[0]}")
print(f"\n First column: \n {tensor_randn[:, 0]}")
print(f"\n Last column: {tensor_randn[..., -1]}")
print(f"\n Selected columns: \n {tensor_randn[:,2:4]}")
## Assignment of column to zero
tensor_randn[:,1] = 0
print("\n Assigning column to zero: \n", tensor_randn)

First row:  
tensor([-1.3470,  0.2204,  0.2963, -0.9745])

 First column: 
 tensor([-1.3470,  0.1867,  0.0517])

 Last column: tensor([-0.9745, -1.2987, -0.4778])

 Selected columns: 
 tensor([[ 0.2963, -0.9745],
        [-1.1872, -1.2987],
        [ 0.3584, -0.4778]])

 Assigning column to zero: 
 tensor([[-1.3470,  0.0000,  0.2963, -0.9745],
        [ 0.1867,  0.0000, -1.1872, -1.2987],
        [ 0.0517,  0.0000,  0.3584, -0.4778]])


### Concatenation 

The `torch.cat` function can be used to concatenate or join multiple tensors together, which is often useful when working with deep learning models. 

Let's take our previous defined tensors and check their shape.

In [42]:
tensor_ones.shape, tensor_zeros.shape, tensor_rand.shape

(torch.Size([3, 4]), torch.Size([3, 4]), torch.Size([3, 4]))

We can concatenate these tensors  column wise by using `torch.cat` with `dim=1`. We will get a resultant tensor with shape (3,12).

In [44]:
concat_tensor = torch.cat([tensor_ones, tensor_zeros, tensor_rand], dim=1)
print(concat_tensor.shape)
concat_tensor

torch.Size([3, 12])


tensor([[1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8675,
         0.0161, 0.5472, 0.7002],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6551,
         0.3049, 0.4088, 0.6341],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2363,
         0.8951, 0.0335, 0.5779]])

We can concatenate these tensors  row wise by using `torch.cat` with `dim=0`. We will get a resultant tensor with shape (9,4).

In [45]:
concat_tensor = torch.cat([tensor_ones, tensor_zeros, tensor_rand], dim=0)
print(concat_tensor.shape)
concat_tensor

torch.Size([9, 4])


tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.8675, 0.0161, 0.5472, 0.7002],
        [0.6551, 0.3049, 0.4088, 0.6341],
        [0.2363, 0.8951, 0.0335, 0.5779]])

### Arithmetic operations

In PyTorch, you can perform arithmetic operations on tensors in a similar way to how you would perform them on numpy arrays. Lets look at some common 
you can perform with PyTorch tensors include element wise addition, subtraction, multiplication, division.

## References

- [Pytorch tensors tutorial documentation](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html).
