---
title: Tensors 
---

## What are Tensors?

PyTorch provides tensors as its primary data structure. Tensors are similar to numpy arrays, but they can be used on a GPU to accelerate the computation. PyTorch tensors are similar to numpy arrays, but they have additional functionality (automatic differentiation) and are designed to take advantage of GPUs for acceleration. Similar to numpy, tensors in PyTorch supports a variety of operations, including indexing, slicing, math operations, linear algebra operations, and more. Let's dive in by importing the library.  

In [2]:
import torch
import numpy as np

## Initializing a Tensor

There are several ways to initialize tensors in PyTorch. Here are some examples:

**Initializing from an iterator like a list**



In [8]:
import torch

# Initialize a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("Tensor from list: \n", tensor_from_list)

# Initialize a tensor from a nested list
tensor_from_nested_list = torch.tensor([[1, 2], [3, 4]])
print("Tensor from nested list: \n", tensor_from_nested_list)

Tensor from list: 
 tensor([1, 2, 3, 4])
Tensor from nested list: 
 tensor([[1, 2],
        [3, 4]])


**Initializing from a numpy array**

In [9]:
# Create a NumPy array
numpy_array = np.array([[1, 2], [3, 4]])

# Initialize a tensor from a NumPy array
tensor_from_numpy = torch.from_numpy(numpy_array)
print("Tensor from np array: \n", tensor_from_numpy)

Tensor from np array: 
 tensor([[1, 2],
        [3, 4]])


**Initializing from another tensor**

In [13]:
# Create a tensor
original_tensor = torch.tensor([1, 2, 3, 4])

# Initialize a new tensor from the original tensor
new_tensor = original_tensor.clone()
print("Tensor from another tensor: \n", new_tensor)

Tensor from another tensor: 
 tensor([1, 2, 3, 4])


**Constant or random initialization**

In [15]:
# Initialize a tensor with all elements set to zero
tensor_zeros = torch.zeros(3, 4)
print("Tensor with all elements set to zero: \n", tensor_zeros)

# Initialize a tensor with all elements set to one
tensor_ones = torch.ones(3, 4)
print("\n Tensor with all elements set to one: \n", tensor_ones)

# Initialize a tensor with all elements set to a specific value
tensor_full = torch.full((3, 4), fill_value=2.5)
print("\n Tensor with all elements set to a specific value: \n", tensor_full)

# Initialize a tensor with random values
tensor_rand = torch.rand(3, 4)
print("\n Tensor with random initialization: \n", tensor_rand)

# Initialize a tensor with random values from a normal distribution
tensor_randn = torch.randn(3, 4)
print("\n Tensor with random values from a normal distribution: \n", tensor_randn)

Tensor with all elements set to zero: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

 Tensor with all elements set to one: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 Tensor with all elements set to a specific value: 
 tensor([[2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000]])

 Tensor with random initialization: 
 tensor([[0.8675, 0.0161, 0.5472, 0.7002],
        [0.6551, 0.3049, 0.4088, 0.6341],
        [0.2363, 0.8951, 0.0335, 0.5779]])

 Tensor with random values from a normal distribution: 
 tensor([[ 1.0550,  0.9214, -1.3023,  0.4119],
        [-0.4691,  0.8733,  0.7910, -2.3932],
        [-0.6304, -0.8792,  0.4188,  0.4221]])


## References

- [Pytorch tensors tutorial documentation](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html).
